'use strict';

// Splitting a report into what is free and what is bought.
//
// The child does a twenty-minute assessment. Holding all of it hostage would
// be a poor trade for them, so two sections stay free whatever happens:
//
//   "Surat"          — the portrait: what this child is good at. Real, specific
//                      content that proves the report is about THEM and not a
//                      template, which is also what makes the rest worth buying.
//   "<name> uchun xat" — the letter written to be read aloud to the child. It is
//                      addressed to them; charging their parent to read it to
//                      them is not a thing this product should do.
//
// Everything a parent would act on — where the child stands, the talents map,
// the interests compass, the learning style, the roadmap, clubs and sports —
// is what the payment unlocks.

// Headings are generated by the model from the prompt in services/prompt.js.
// The letter's heading carries the child's name, so it is matched by shape.
const FREE_EXACT = ['surat'];
const FREE_PATTERNS = [/uchun xat$/i];

const norm = (s) => String(s || '').trim().toLowerCase();

function isFreeHeading(title) {
  const t = norm(title);
  return FREE_EXACT.includes(t) || FREE_PATTERNS.some((re) => re.test(t));
}

// Split markdown on level-2 headings, keeping each heading with its body.
// Anything before the first heading (a stray intro line) travels with the free
// part: it is never the substance, and dropping it would look like a bug.
function sections(md) {
  const out = [];
  const lines = String(md || '').split('\n');
  let cur = { title: null, lines: [] };
  for (const line of lines) {
    const m = /^##\s+(.+?)\s*$/.exec(line);
    if (m) {
      out.push(cur);
      cur = { title: m[1], lines: [line] };
    } else {
      cur.lines.push(line);
    }
  }
  out.push(cur);
  return out.filter((s) => s.title !== null || s.lines.join('').trim() !== '');
}

// Returns the visible markdown plus the titles of what is withheld, so the
// page can show a parent exactly what they would be buying rather than an
// unexplained wall.
function split(md) {
  const secs = sections(md);
  const free = [];
  const lockedTitles = [];
  for (const s of secs) {
    if (s.title === null || isFreeHeading(s.title)) free.push(s.lines.join('\n'));
    else lockedTitles.push(s.title);
  }
  return { freeMd: free.join('\n').trim(), lockedTitles };
}

// The public shape of a report, with everything behind the paywall removed
// when it has not been bought. Structured findings (levels, sports) are part
// of what is sold, so they are withheld too — leaving them in the JSON would
// hand over the headline result to anyone who opened the network tab.
function publicReport(r, { paid, priceUzs }) {
  const base = {
    nickname: r.nickname,
    grade: r.grade,
    partial: r.partial,
    date: r.created_at,
  };
  if (paid) {
    return {
      ...base,
      locked: false,
      content_md: r.content_md,
      levels: { logic: r.level_logic, psych: r.level_psych, activity: r.level_activity },
      sports: r.sports,
    };
  }
  const { freeMd, lockedTitles } = split(r.content_md);
  return {
    ...base,
    locked: true,
    content_md: freeMd,
    locked_sections: lockedTitles,
    price_uzs: priceUzs,
    // Nulled rather than omitted so the client's shape does not change between
    // the two states and every consumer has to handle one object, not two.
    levels: { logic: null, psych: null, activity: null },
    sports: [],
  };
}

module.exports = { split, sections, isFreeHeading, publicReport };
